
@template('template.t-tut')

  <!-- @lay('build.co.coords:header') -->

  @lay('build.co.navbars:left-nav')

  <div class="box-full pxl-2 bc-white pull-right">
    
    <section class="pxv-10 tutorial mails bc-white">
      <div class="font-em-1d2">

        <div class="start font-em-d8">

          @lay('build.co.links:tutor_pointer') <br>

          <div class="font-em-1d5 c-orange">Mails : response</div> <br>  
          
          <div class="pulling-data">

              <div class="fb-6">
                  <div class=" fb-6 bc-white-dd flex-full rad-4 pxv-8 lacier">
                  <div class="flex-full midv"> 
                      <span class="bi-speaker mxr-8 c-lime-dd"></span> Responses
                  </div>
                  </div>
              </div> <br>

              <div class="">

                <div class="">
                    In the course of handling mails, developers tend to get responses of their mails. 
                    The <code>response()</code> method does this in the mailer tool. It simply return the 
                    responses of mails. These response is an array that includes the messages generated by
                    the mailer and also the content of the mail itself which can be good for preview. It is 
                    important to emphasize that a mail may not look entirely similar to a preview for certain 
                    reasons as some stylesheets may not be accepted in mails.
                </div>

              </div> 
          </div> <br>
          
          <div id="pull" class="content"> 
              
              <div>
                  Here is an example below
              </div>

              <div class="file-setup">
                <div class="pre-area shadow">
                  <div class="box-full">
    <div class="pxv-6 bc-off-white"><code>Sample: Getting mails responses</code></div>
    <pre class="pre-code">
  &#60;?php

    $mailer = new Mailer;
    
    $mailer->authorize(true);

    $mailer->server('mail.server'); 
    
    $mailer->setup([

        'client' => ['name' => 'Foo']

    ]);

    $mailer->sendmail('mail.template');
    
    if($mail->sent('online') || $mail->sent('offline')) {      

        var_dump($mailer->response()); <span class="comment">// returns: messages</span>

    }
    </pre>
                  </div>
                </div>
              </div>

              <div class=" font-em-d8 pvs-6">
                  In the example above, <code>response()</code> method returns the response of the mail.
              </div>

          </div> <br>

          @lay('build.co.links:tutor_pointer')

        </div>
      </div>
    </section>

  </div>
    
  @lay('build.co.coords:footer')

@template;