<?php 

namespace spoova\mi\core\classes\Ghost;

use Closure;
use stdClass;
use Exception;
use ErrorException;
use ReflectionFunction;
use ReflectionNamedType;
use ReflectionUnionType;
use InvalidArgumentException;
use spoova\mi\core\classes\EInfo;
use spoova\mi\core\classes\ValueType;
use spoova\mi\core\commands\Root\Cli;

/**
 * This class generates anonymous functions that are 
 * accessible as methods of a class. This process is generated by 
 *  1. Defining anonymous methods' access names during instantiation
 *  2. Defining an immutable anonymous closure function by first accessing it's predefined access name 
 *  3. Once defined, anonymous method can be triggered through its access name
 *  4. Access names of stored anonymous functions can be viewed as a public property but cannot be modified.
 * 
 *  - Warning: GhostFunctions are not supported by IDEs used, hence, when used a full documention of the 
 * methods accessible must be clearly documented on functions or methods from which they are returned as objects.
 */
class GhostFunction extends stdClass {

    /**
     * Contains the properties accessed as methods
     *
     * @var array
     */
    private array $FunctionsList = [];

    /**
     * Defines when a property is allowed to be assigned
     *
     * @var boolean
     */
    private bool $PropertySet = false;

    /**
     * Defines the name of a Ghost method.
     *
     * @var string
     */
    private string $FunctionsListName = '';

    /**
     * Defines a value returned by __toString()
     *
     * @var string
     */    
    private string $FunctionsListMain;

    /**
     * Defines the current value of a property
     *
     * @var array
     */    
    private array $GhostProperties = [];

    private bool $FunctionsListInit = false;

    public const properties = 'properties';
    public const methods = 'methods';

    /**
     * Define only accepted properties
     *
     * @param array $props array values where value is an assumed property that is non-numerical and non-empty string
     * @param string $name assigns a name for function list
     */
    final public function __construct(array|string $props = [], string $name = '')
    {
        
        if($this->FunctionsListInit === false){

            $this->FunctionsListInit = true;

            $props = is_string($props)? explode(',',$props) : $props;
            
            foreach($props as $value){
                $main = false;
                
                if(is_array($value)){
                    if(count($value) === 1){
                        $key = array_keys($value)[0];
                        $val = array_values($value)[0];
                        if(!array_key_exists($key, $this->GhostProperties)){
                            $this->GhostProperties[$key] = $val;
                        }
                        continue;
                    }else{
                        throw new InvalidArgumentException('array values must be a count of one key and value pair');
                    }
                }elseif(is_string($value)){

                    if(method_exists($this, $value)){
                        throw new InvalidArgumentException('defining a reserved GhostFunction method "'.Cli::warn($value).'" is denied!');
                    }
                    if(substr($value, 0, 2) === '::'){
                        if(!isset($this->FunctionsListMain)){
                            $value = substr($value, 2);
                            $main = true;
                        }else{
                            throw new InvalidArgumentException('there can be only one main property returned as GhostFunction string');
                        }
                    }
                }

                if(!(is_string($value) && preg_match("/[A-Za-z_][A-Za-z_0-9]*?/", $value))){
                    throw new InvalidArgumentException('array value must be a valid accessible string to be assumed as property');
                }

                $this->FunctionsList[$value] = $this;
                $this->FunctionsListName = $name;
                if($main) $this->FunctionsListMain = $value;
            }
            
        }

    }

    /**
     * Set a property only allowed internally
     *
     * @param string $name
     */
    final public function __get($name)
    {
        if(array_key_exists($name, $this->GhostProperties)){
            return $this->GhostProperties[$name];
        }
        $funcName = $this->FunctionsListName;
        $funcDesc = trim($funcName)? $funcName : 'anonymous GhostFunction class';
        throw new ErrorException('the "'.$name.'" anonymous property is not defined for '.$funcDesc);
    }

    /**
     * Set a property only allowed internally
     *
     * @param string $name
     * @param mixed $value
     */
    final public function __set($name, $value)
    {
        if($this->PropertySet){
            $this->$name = $value;
        }else{
            $called = $name?: "__set()";
            $funcName = $this->FunctionsListName;
            $funcDesc = trim($funcName)? $funcName : 'anonymous GhostFunction class';
            throw new ErrorException('the "'.$name.'" property does not exist as a valid property of '.$funcDesc);
        }
    }

    /**
     * Handler for invoked anonymous method
     *
     * @param string $name method name
     * @param array $arguments arguments
     * @return void
     */
    final public function __call($name, $arguments)
    {
        $FunctionsList = $this->FunctionsList;

        if(!array_key_exists($name, $FunctionsList)){
            $funcName = $this->FunctionsListName;
            $funcDesc = trim($funcName)? $funcName : 'this class';
            throw new Exception('invoked method "'.$name.'" is not a valid property of '.$funcName);
        }

        if($FunctionsList[$name] instanceof Closure) {
            $closure = $FunctionsList[$name]; 
            $reflection = new ReflectionFunction($closure);
            $parameters = $reflection->getParameters();
            $required = $reflection->getNumberOfRequiredParameters();
            if($required > count($arguments)){
                throw new Exception('invalid number of arguments supplied on "'.$name.'" method');
            }
            foreach($parameters as $key => $parameter){
                $type =  $parameter->getType(); // get the type(s) of parameter supplied
                $types = [];

                if($type instanceof ReflectionUnionType){
                    $types = array_map(fn($t) => $t->getName(), $type->getTypes());
                }else if($type instanceof ReflectionNamedType){
                    $types = [$type->getName()];
                }

                if($types && ($arguments && isset($arguments[$key]))){
                    if(is_object($arguments[$key])){
                        if(!in_array('object',$types) && !in_array(get_class($arguments[$key]), $types)){
                            throw new Exception('argument [#'.$key.'] supplied on "'.$name.'" method must be of type ('.implode('|', $types).')');
                        }
                    }else{
                        if(!ValueType::inType($arguments[$key], $types)){
                            throw new Exception('argument [#'.$key.'] supplied on "'.$name.'" method must be of type ('.implode('|', $types).')');
                        }
                    }
                }

            }
            return $closure(...$arguments);
        }elseif($FunctionsList[$name] === $this){
            if((count($arguments) === 1) && ($arguments[0] instanceof Closure)){
                if(!array_key_exists($name, $this->GhostProperties)){
                    $this->PropertySet = true;
                    $this->$name = $arguments[0];
                    $this->PropertySet = false;
                }
                $this->FunctionsList[$name] = $arguments[0];
            }else{
                if(count($arguments) === 0) throw new ErrorException('calling "'.$name.'" method before callback registration');
                throw new ErrorException('defined function must be a single closure argument');
            }
        }
    }

    /**
     * Retrieve GhostFunction methods or properties
     *
     * @param string $type optional [GhostFunction::methods|GhostFunction::properties]
     * @return array
     */
    public function ghosts(string $type = GhostFunction::methods) {
        if($type === GhostFunction::methods){
            $methods = array_keys($this->FunctionsList); // custom methods
            $extended =  get_class_methods($this); // extended methods 
            return array_unique(array_merge($methods, $extended));
        }else{
            return array_keys($this->GhostProperties);
        }
    }

    public function __toString()
    {
        $function = $this->FunctionsListMain;
        $response = $this->{$function}();
        if(!is_string($response)) {
            $backTrace = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);
            if(count($backTrace) > 1){
                $file = $backTrace[1]['file']?? '';
                $line = $backTrace[1]['line']?? '';
                return EInfo::view("object of GhostFunction cannot be converted to string in $file on $line");
            }
        }
        return $response;
    }

}