<?php

namespace spoova\mi\tests\Unit\Routing;

use PHPUnit\Framework\TestCase;
use spoova\mi\core\classes\Router;

/**
 * Covers Router::map(), which reads and decodes the project route map
 * (windows/Routes/.map) into an array.
 *
 * The map file is generated by the route commands, so it is not guaranteed to
 * exist in a given checkout — an earlier version of this test asserted against
 * whatever the project happened to ship and failed on any clone that had not
 * built one yet. Each test now writes the map it wants to read and puts the
 * original back afterwards.
 */
class RouterMapTest extends TestCase
{
    private string $mapFile;

    /** Contents of the project's own map file, restored in tearDown(). */
    private ?string $original = null;

    protected function setUp(): void
    {
        $this->mapFile = to_frontslash(WIN_ROUTES).'.map';

        if (!is_dir($directory = dirname($this->mapFile))) {
            mkdir($directory, 0777, true);
        }

        if (is_file($this->mapFile)) {
            $this->original = (string) file_get_contents($this->mapFile);
        }
    }

    protected function tearDown(): void
    {
        if ($this->original !== null) {
            file_put_contents($this->mapFile, $this->original);
        } elseif (is_file($this->mapFile)) {
            unlink($this->mapFile);
        }
    }

    /** Puts $contents in the place Router::map() reads from. */
    private function writeMap(string $contents): void
    {
        file_put_contents($this->mapFile, $contents);
    }

    /* ---- decoding ---- */

    public function test_map_decodes_the_map_file(): void
    {
        $this->writeMap(json_encode([':root' => ['*' => 'home'], 'blog' => ['*' => 'blog\\Index']]));

        $map = Router::map();

        $this->assertSame(['*' => 'home'], $map[':root']);
        $this->assertSame(['*' => 'blog\\Index'], $map['blog']);
    }

    public function test_map_populates_by_reference_argument(): void
    {
        $this->writeMap(json_encode([':root' => ['*' => 'home']]));

        $ref = [];
        $return = Router::map($ref);

        $this->assertSame($return, $ref, 'The by-reference argument should mirror the return value.');
    }

    /* ---- a map that cannot be read ---- */

    /**
     * A project that has not generated its map yet is a normal state, not an
     * error — dispatch falls back to its own defaults on an empty map.
     */
    public function test_a_missing_map_file_reads_as_an_empty_map(): void
    {
        if (is_file($this->mapFile)) {
            unlink($this->mapFile);
        }

        $this->assertSame([], Router::map());
    }

    public function test_a_corrupt_map_file_reads_as_an_empty_map_rather_than_null(): void
    {
        $this->writeMap('{not valid json');

        $map = Router::map();

        $this->assertIsArray($map, 'A failed json_decode() must not leak NULL to the caller.');
        $this->assertSame([], $map);
    }

    /**
     * Valid JSON that is not an object/array still decodes — to a scalar. The
     * caller is typed to an array, so that has to be flattened too.
     */
    public function test_a_scalar_map_file_reads_as_an_empty_map(): void
    {
        $this->writeMap('"just a string"');

        $this->assertSame([], Router::map());
    }

    public function test_an_empty_map_file_reads_as_an_empty_map(): void
    {
        $this->writeMap('');

        $this->assertSame([], Router::map());
    }

    /**
     * The by-reference argument is the only result an unread map has; leaving a
     * caller's pre-seeded array in place would let a stale map look like a fresh one.
     */
    public function test_the_reference_is_emptied_when_the_map_cannot_be_read(): void
    {
        if (is_file($this->mapFile)) {
            unlink($this->mapFile);
        }

        $ref = [':root' => ['*' => 'stale']];
        Router::map($ref);

        $this->assertSame([], $ref);
    }
}
